version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

x-database-variables: &database-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


x-app-variables: &app-variables
  <<: *database-variables
  DB_HOST: ${DB_HOST}

services:
  website:
    image: mysite-tutorial:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - db_migrate

    ports:
      - "8000:8000"
    env_file:
      - .env
  db_migrate:
    image: mysite-tutorial:latest
    command: python manage.py migrate
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    image: postgres:18
    ports: 
      - "5432:5432"
    environment: *database-variables
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db-data: